<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hotel =[
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/sunriverside/Sunriverside.png'), 'name'=>'DaNang Sun Riverside Hotel & Spa','location'=>'Son Tra Peninsula', 'address'=>'Ho Son Thanh, Hoa Hai Ward, Ngu Hanh Son District', 'description'=>'A luxurious riverside resort', 'rate'=>'3',],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/hanami/Hanami.jpg'), 'name'=>'Hanami Hotel Danang','location'=>'My Khe Beach', 'address'=>'61-63 Hoang Ke Viem Street, Ngu Hanh Son District', 'description'=>'The budget hotel has a coffee shop, a covered terrace, simply furnished rooms, some rooms with balconies.', 'rate'=>'3'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/Grandvrio/Grandvrio.jpg'), 'name'=>'Grandvrio City DaNang','location'=>'Hai Chau District', 'address'=>'Lot G, Khu Do Thi My An, Ngu Hanh Son District', 'description'=>'A modern resort close to the beach', 'rate'=>'3'],
            ['idCategoryHotel'=>'3','image'=>Storage::url('public/images/RoyalLotus/RoyalLotus.jpg'), 'name'=>'Royal Lotus Hotel DaNang','location'=>'Phuoc My Ward', 'address'=>'28 Vo Nguyen Giap Street, Khanh Hoa Ward, Ngu Hanh Son District', 'description'=>'An upscale hotel with contemporary amenities', 'rate'=>'3'],
            ['idCategoryHotel'=>'2','image'=>Storage::url('public/images/SeaWonder/SeaWonder.jpg'), 'name'=>'Sea Wonder Hotel','location'=>'My Khe Beach', 'address'=>'Lot 15 - Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, DaNang City, Vietnam', 'description'=>'Comfortable and affordable hotel close to the beach', 'rate'=>'3'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/paradise/paradise.jpg'), 'name'=>'Paradise Hotel','location'=>'City Center', 'address'=>'40 An Thuong 1, My An Ward, Ngu Hanh Son District, DaNang City, Vietnam', 'description'=>'Budget hotel in the heart of DaNang', 'rate'=>'3'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/GrandSea/GrandSea.jpg'), 'name'=>'Grand Sea View Hotel & Spa','location'=>'Ngu Hanh Son District', 'address'=>'121 Hoang Ke Viem Street, Ngu Hanh Son District, DaNang City, Vietnam', 'description'=>'Affordable and social hostel in downtown DaNang', 'rate'=>'3'],
            ['idCategoryHotel'=>'1','image'=>Storage::url('public/images/MinhToan/MinhToan.jpg'), 'name'=>'Minh Toan Hotel','location'=>'City Center', 'address'=>'28 Phan Dinh Phung, Hai Chau District, DaNang City, Vietnam', 'description'=>'Budget hotel in the center of DaNang', 'rate'=>'3'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/SilverSea/SilverSea.jpg'), 'name'=>'Silver Sea Hotel','location'=>'My Khe Beach', 'address'=>'Lot 9-10 Vo Van Kiet Street, My An Ward, Ngu Hanh Son District, DaNang City, Vietnam', 'description'=>'Affordable hotel near the beach', 'rate'=>'3'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/DaNangPetro/DaNangPetro.jpg'), 'name'=>'DaNang Petro Hotel & Apartments','location'=>'Son Tra District', 'address'=>'230 Nguyen Huu Tho Street, My An Ward', 'description'=>'This hotel offers affordable apartments and hotel rooms.', 'rate'=>'3'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/HadanaBoutique/HadanaBoutique.jpg'), 'name'=>'Hadana Boutique Hotel DaNang','location'=>'Hai Chau District', 'address'=>'23 Phan Boi Chau, Hai Chau District', 'description'=>'This hotel features modern rooms with city views.','rate'=>'3'],
            ['idCategoryHotel'=>'2','image'=>Storage::url('public/images/Brilliant/BrilliantHotel.jpg'), 'name'=>'Brilliant Hotel DaNang','location'=>'Hai Chau District', 'address'=>'162 Bach Dang Street, Hai Chau District', 'description'=>'This hotel is located near the Han River and features modern rooms.','rate'=>'3'],
            ['idCategoryHotel'=>'1','image'=>Storage::url('public/images/DanangCenter/DanangCenter.jpg'), 'name'=>'DaNang Center Hotel','location'=>'Hai Chau District', 'address'=>'35 Huynh Thuc Khang, Hai Chau District', 'description'=>'This hotel is located in the heart of Da Nang and features comfortable rooms.', 'rate'=>'3'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/3stars/snouva.jpg'), 'name'=>'Sanouva DaNang Hotel','location'=>'Hai Chau District', 'address'=>'68 Phan Chau Trinh Street, Hai Chau District', 'description'=>'This hotel offers stylish rooms with modern amenities.', 'rate'=>'3'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/3stars/queenhotel.png'), 'name'=>'Queen\'s Finger Hotel Da Nang','location'=>'Hai Chau District', 'address'=>'75 Phan Chu Trinh, Hai Chau District', 'description'=>'This hotel features comfortable rooms and is located near the Han River', 'rate'=>'3'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/3stars/orange-Hotel.png'), 'name'=>'Orange Hotel DaNang','location'=>'Son Tra District', 'address'=>'21/2 Ha Bong, My An Ward', 'description'=>'This hotel offers modern rooms with city views.','rate'=>'3'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/3stars/starlet-hotel.jpg'), 'name'=>'Starlet Hotel DaNang','location'=>'Hai Chau District', 'address'=>'227 Tran Phu Street, Hai Chau District', 'description'=>'This hotel offers comfortable rooms in a central location.','rate'=>'3'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/3stars/Parze-hotel.png'), 'name'=>'Parze Ocean Hotel & Spa','location'=>'Ngu Hanh Son District', 'address'=>'91 An Thuong 1, Ngu Hanh Son District', 'description'=>'This hotel features a spa and is located near the beach.','rate'=>'3'],
            ['idCategoryHotel'=>'2','image'=>Storage::url('public/images/3stars/coco-hotel.jpg'), 'name'=>'Coco Hotel DaNang','location'=>'Son Tra District', 'address'=>'269 Nguyen Van Thoai, My An Ward', 'description'=>'This hotel offers modern rooms with city views.','rate'=>'3'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/3stars/Sun-River-Hotel.jpg'), 'name'=>'Sun River Hotel','location'=>'Hai Chau District', 'address'=>'132-134 Bach Dang Street, Hai Chau District	', 'description'=>'This hotel is located near the Han River and features comfortable rooms.	', 'rate'=>'3'],

            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/4stars/Novotel.jpg'), 'name'=>'Novotel DaNang Premier Han River','location'=>'City Center', 'address'=>'36 Bach Dang Street, Hai Chau District, Da Nang', 'description'=>'A modern hotel with panoramic river views', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/Orange-Hotel-4-star.png'), 'name'=>'Orange Hotel Danang','location'=>'City Center', 'address'=>'20 Thai Phien Street, Hai Chau District, Da Nang', 'description'=>'A colorful hotel with a great location', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/minh-toan.jpg'), 'name'=>'Minh Toan Hotel','location'=>'City Center', 'address'=>'31 Tran Phu Street, Hai Chau District, Da Nang', 'description'=>'A sleek hotel with minimalist decor', 'rate'=>'4'],
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/4stars/grand-mercure.jpg'), 'name'=>'Grand Mercure Danang','location'=>'Son Tra Peninsula', 'address'=>'Lot A1 Zone of the Villas of Green Island, Hoa Cuong Bac Ward, Hai Chau District, Da Nang', 'description'=>'A beachfront resort with luxurious amenities', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/risemount-premier.jpg'), 'name'=>'Risemount Premier Resort Danang','location'=>'City Center', 'address'=>'120 Nguyen Van Thoai Street, Ngu Hanh Son District, Da Nang', 'description'=>'A resort-style hotel with lush gardens', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/altara-suite.jpg'), 'name'=>'Altara Suites','location'=>'City Center', 'address'=>'120 Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, Da Nang', 'description'=>'Luxury serviced apartments in the heart of Da Nang', 'rate'=>'4'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/4stars/samdi.png'), 'name'=>'Samdi Hotel','location'=>'City Center', 'address'=>'272 Tran Phu Street, Hai Chau District, Da Nang', 'description'=>'A boutique hotel with modern amenities', 'rate'=>'4'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/4stars/hanada.png'), 'name'=>'Hadana Boutique Hotel','location'=>'City Center', 'address'=>'26 Phan Chu Trinh Street, Hai Chau District, Da Nang', 'description'=>'A charming hotel with unique architecture', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/Sanouva-4-star.jpg'), 'name'=>'Sanouva Danang Hotel','location'=>'City Center', 'address'=>'68 Phan Chau Trinh Street, Hai Chau District, Da Nang', 'description'=>'A stylish hotel with French-inspired design', 'rate'=>'4'],
            ['idCategoryHotel'=>'4','image'=>Storage::url('public/images/4stars/HAIAN.jpg'), 'name'=>'HAIAN Beach Hotel & Spa','location'=>'My Khe Beach', 'address'=>'232 Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A beachfront hotel with contemporary rooms', 'rate'=>'4'],
            ['idCategoryHotel'=>'5','image'=>Storage::url('public/images/4stars/Diamond.jpg'), 'name'=>'Diamond Sea Hotel','location'=>'My Khe Beach', 'address'=>'278 Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A stylish hotel with a rooftop infinity pool', 'rate'=>'4'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/4stars/A-La-Carte.png'), 'name'=>'A La Carte Danang Beach Hotel','location'=>'Ngu Hanh Son District', 'address'=>'200 Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District	', 'description'=>'This trendy hotel is located on the famous My Khe Beach and offers chic accommodations.', 'rate'=>'4'],

            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/InterContinental.jpg'), 'name'=>'InterContinental Danang Sun Peninsula Resort','location'=>'Son Tra Peninsula	', 'address'=>'Bai Bac, Son Tra Peninsula, Da Nang', 'description'=>'A luxury resort with stunning ocean views', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/Pullman.png'), 'name'=>'Pullman Danang Beach Resort','location'=>'Non Nuoc Beach', 'address'=>'101 Vo Nguyen Giap Street, Khue My Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A beachfront resort with modern amenities', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/Fusion-Maia.png'), 'name'=>'Fusion Maia Resort','location'=>'Non Nuoc Beach', 'address'=>'Truong Sa Street, Khue My Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A boutique resort with private pool villas', 'rate'=>'5'],
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/5stars/Sheraton-Grand.png'), 'name'=>'Sheraton Grand Danang Resort','location'=>'Non Nuoc Beach', 'address'=>'35 Truong Sa Street, Hoa Hai Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A luxurious resort with beautiful ocean views', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/Vinpearl-Luxury.jpg'), 'name'=>'Vinpearl Luxury Da Nang','location'=>'Non Nuoc Beach', 'address'=>'Truong Sa Street, Hoa Hai Ward, Ngu Hanh Son District, Da Nang	', 'description'=>'A beachfront resort with private villas', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/NamanRetreat.jpg'), 'name'=>'Naman Retreat','location'=>'Non Nuoc Beach', 'address'=>'Truong Sa Road, Hoa Hai Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A stylish resort with modern villas', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/fusion-suites.jpg'), 'name'=>'Fusion Suites Danang Beach','location'=>'My An Beach', 'address'=>'Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A modern beachfront hotel with spacious suites', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/grand-mercure.jpg'), 'name'=>'Grand Mercure Danang','location'=>'Son Tra Beach', 'address'=>'Lot A1 Zone of the Villas of Green Island, Hoa Cuong Bac Ward, Hai Chau District, Da Nang', 'description'=>'A contemporary beachfront hotel with ocean views', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/hyatt-regency.jpg'), 'name'=>'Hyatt Regency Danang Resort and Spa','location'=>'Son Tra Peninsula', 'address'=>'5 Truong Sa Street, Hoa Hai Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A beachfront resort with stunning ocean views', 'rate'=>'5'],
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/5stars/Premier-Village.jpg'), 'name'=>'Premier Village Danang Resort','location'=>'Vo Nguyen Giap Street', 'address'=>'Vo Nguyen Giap Street, My An Ward, Ngu Hanh Son District, Da Nang', 'description'=>'A beachfront resort with luxurious villas', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/Centara-Sandy-Beach.jpg'), 'name'=>'Centara Sandy Beach Resort Danang','location'=>'Non Nuoc Beach', 'address'=>'21 Truong Sa, Hoa Hai, Ngu Hanh Son, Đa Nang', 'description'=>'A beachfront resort with a variety of amenities', 'rate'=>'5'],
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/5stars/Hilton.jpg'), 'name'=>'Hilton Da Nang','location'=>'Ngu Hanh Son District', 'address'=>'50 Bach Dang Street, Hai Chau District, Da Nang', 'description'=>'A luxury hotel with an oceanfront location and modern amenities.', 'rate'=>'5'],
            ['idCategoryHotel'=>'6','image'=>Storage::url('public/images/5stars/Hilton-Grand.jpg'), 'name'=>'Hilton Grand Vacations Da Nang','location'=>'Hoa Hai Ward', 'address'=>'110 Vo Nguyen Giap, Khue My Ward, Ngu Hanh Son District', 'description'=>'A family-friendly resort with a range of activities for all ages.', 'rate'=>'5'],
            ['idCategoryHotel'=>'7','image'=>Storage::url('public/images/5stars/Hilton3.jpg'), 'name'=>'Hilton Da Nang Beach Resort','location'=>'Ngu Hanh Son District', 'address'=>'Hoang Sa Street, Ngu Hanh Son District, Da Nang', 'description'=>'A luxury beachfront resort with breathtaking views and exquisite cuisine.', 'rate'=>'5'],

        ];
        Hotel::insert($hotel);
    }
}
